### ISSUE TITLE
"TimeoutError: Missing credentials in config"

### ISSUE THREAD

**Issue by webline** [alexa/skill-sample-nodejs-feed#3]
Each time I try to deploy the code of this sample I run into this error:

{ [TimeoutError: Missing credentials in config]
  message: 'Missing credentials in config',
  code: 'CredentialsError',
  time: Wed Mar 22 2017 11:20:34 GMT+0100 (CET),
  originalError: 
   { message: 'Could not load credentials from any providers',
     code: 'CredentialsError',
     time: Wed Mar 22 2017 11:20:34 GMT+0100 (CET),
     originalError: 
      { message: 'Connection timed out after 1000ms',
        code: 'TimeoutError',
        time: Wed Mar 22 2017 11:20:34 GMT+0100 (CET) } } } 'TimeoutError: Missing credentials in config\n    at ClientRequest.<anonymous> (/Users/xyz/Documents/svn lokal/alexa_feed/skill-sample-nodejs-feed/bin/node_modules/aws-sdk/lib/http/node.js:56:34)\n    at ClientRequest.g (events.js:180:16)\n    at ClientRequest.emit (events.js:92:17)\n    at Socket.emitTimeout (http.js:1798:10)\n    at Socket.g (events.js:180:16)\n    at Socket.emit (events.js:92:17)\n    at Socket._onTimeout (net.js:327:8)\n    at _makeTimerTimeout (timers.js:438:11)\n    at Timer.unrefTimeout [as ontimeout] (timers.js:502:5)'

I do have a valid credentials file in my ~/.aws directory. The only thing that is different from your sample: I use EU/Ireland as region. This is set in my ~/.aws config file too.

Any ideas?

**Comment by jankutschera** [comment]
Same here with using US East N.Virginia

**Comment by jankutschera** [comment]
It worked after correcting the path to .aws directory like here: 
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by webline** [comment]
the problem was the credentials file. I wrote the values according to the samples from Amazon:

AWSAccessKeyId=xxxxxxxx
AWSSecretKey=yyyyy

But the working format is:
aws_access_key_id = xxxxxxx
aws_secret_access_key = yyyyyy

**Comment by aleminopuy** [comment]
I'm running into the same, but I think my problem is I don't know where to put that credentials file (/.aws I think?) but more importantly, what do I name the file?

**Comment by aleminopuy** [comment]
Perhaps I found my answer (in the link @jankutschera shared above):

Configuration Settings and Precedence

The AWS CLI uses a provider chain to look for AWS credentials in a number of different places, including system or user environment variables and local AWS configuration files.

The AWS CLI looks for credentials and configuration settings in the following order:

Command Line Options – region, output format and profile can be specified as command options to override default settings.

Environment Variables – AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, etc.

The AWS credentials file – located at ~/.aws/credentials on Linux, macOS, or Unix, or at C:\Users\USERNAME \.aws\credentials on Windows. This file can contain multiple named profiles in addition to a default profile.

The CLI configuration file – typically located at ~/.aws/config on Linux, macOS, or Unix, or at C:\Users\USERNAME \.aws\config on Windows. This file can contain a default profile, named profiles, and CLI specific configuration parameters for each.

Instance profile credentials – these credentials can be used on EC2 instances with an assigned instance role, and are delivered through the Amazon EC2 metadata service.

**Comment by nancyletsnurture** [comment]
Do we need to add region and initialize s3 bucket, in case if s3 bucket is added

**Comment by nancyletsnurture** [comment]
First download  - _**curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"**_ , now unzip with -  **unzip awscli-bundle.zip_** . Now, The Final Step is to install executable and test the AWS CLI installation - **sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws** . Now you can  test if correctly installed  with **aws help** and then finally you can connect your AWS environment in terminal and add   
 $ aws configure
AWS Access Key ID [None]: Your Access Key
AWS Secret Access Key [None]: Your Secret Key
Default region name [None]: us-west-2
Default output format [None]: json

and it will be done.
